# -*- coding: utf-8 -*-
"""Major Project 2 Backend fin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b45vT4pLu6jtHkU0APCZbX1-yNY-pONG
"""



# ============================================================
# FINAL DRUG–DISEASE SIMULATION (STABLE + NO NaN + TRAIN-TEST)
# ============================================================

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, Model
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from rdkit import Chem
from rdkit.Chem import Descriptors, Crippen, Lipinski, rdMolDescriptors

import torch
from transformers import AutoTokenizer, AutoModel

# ============================================================
# LOAD DATASET
# ============================================================

df = pd.read_csv("drug_data_updated.csv")
df = df.dropna(subset=["SMILES"])
df = df.drop_duplicates(subset=["SMILES"])

dataset_lookup = df.set_index("SMILES").to_dict(orient="index")

# ============================================================
# SAFE TARGET GENERATION (CRITICAL FIX)
# ============================================================

def generate_targets(row):

    logP = np.clip(row["LogP"], -5, 5)
    TPSA = np.clip(row["TPSA"], 1e-3, 200)

    binding = 1 / (1 + np.exp(-logP))
    pathway = binding * 0.8

    tox_input = 0.3 * logP - 0.1 * TPSA
    tox_input = np.clip(tox_input, -10, 10)

    toxicity = 1 / (1 + np.exp(-tox_input))

    return binding, pathway, toxicity

targets = df.apply(generate_targets, axis=1)

df["Binding_Theoretical"] = [t[0] for t in targets]
df["Pathway_Theoretical"] = [t[1] for t in targets]
df["Toxicity_Theoretical"] = [t[2] for t in targets]

# ============================================================
# TRAIN-TEST SPLIT
# ============================================================

train_df, test_df = train_test_split(df, test_size=0.1, random_state=42)

print(f"Train size: {len(train_df)} | Test size: {len(test_df)}")

# ============================================================
# LOAD TRANSFORMER (ONCE)
# ============================================================

tokenizer = AutoTokenizer.from_pretrained("seyonec/ChemBERTa-zinc-base-v1")
transformer_model = AutoModel.from_pretrained("seyonec/ChemBERTa-zinc-base-v1")

# ============================================================
# EMBEDDING CACHE (SPEED + STABILITY)
# ============================================================

embedding_cache = {}

def smiles_to_embedding(smiles):

    if smiles in embedding_cache:
        return embedding_cache[smiles]

    inputs = tokenizer(smiles, return_tensors="pt", padding=True, truncation=True)

    with torch.no_grad():
        outputs = transformer_model(**inputs)

    emb = outputs.last_hidden_state.mean(dim=1).numpy().flatten()
    emb = np.nan_to_num(emb)

    embedding_cache[smiles] = emb
    return emb

# ============================================================
# RDKit FEATURES
# ============================================================

def extract_features(smiles):

    mol = Chem.MolFromSmiles(str(smiles))
    if mol is None:
        return None

    feats = np.array([
        Descriptors.MolWt(mol),
        Crippen.MolLogP(mol),
        Lipinski.NumHDonors(mol),
        Lipinski.NumHAcceptors(mol),
        rdMolDescriptors.CalcTPSA(mol),
        rdMolDescriptors.CalcNumRotatableBonds(mol),
        Descriptors.NumAromaticRings(mol)
    ], dtype=np.float32)

    feats = np.clip(feats, -1e3, 1e3)
    return np.nan_to_num(feats)

# ============================================================
# FEATURE BUILDER
# ============================================================

def build_features(smiles):

    if smiles in dataset_lookup:
        row = dataset_lookup[smiles]
        rdkit = np.array([
            row["MolWt"], row["LogP"], row["HBD"],
            row["HBA"], row["TPSA"], row["RotBonds"],
            row["AromaticRings"]
        ], dtype=np.float32)
    else:
        rdkit = extract_features(smiles)
        if rdkit is None:
            return None

    emb = smiles_to_embedding(smiles)

    combined = np.concatenate([rdkit, emb])

    # CRITICAL STABILITY FIX
    combined = np.clip(combined, -1e3, 1e3)
    combined = np.nan_to_num(combined)

    return combined

# ============================================================
# BUILD TRAIN DATA
# ============================================================

X_train, y_train = [], []

for _, row in train_df.iterrows():

    feats = build_features(row["SMILES"])
    if feats is None:
        continue

    X_train.append(feats)

    y_train.append([
        row["Binding_Theoretical"],
        row["Pathway_Theoretical"],
        row["Toxicity_Theoretical"]
    ])

X_train = np.array(X_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)

# CLEAN
X_train = np.nan_to_num(X_train)
y_train = np.nan_to_num(y_train)

# REMOVE EXTREME SAMPLES
mask = (np.abs(X_train).max(axis=1) < 1e4)
X_train = X_train[mask]
y_train = y_train[mask]

# ============================================================
# BUILD TEST DATA
# ============================================================

X_test, test_smiles = [], []

for _, row in test_df.iterrows():

    feats = build_features(row["SMILES"])
    if feats is None:
        continue

    X_test.append(feats)
    test_smiles.append(row["SMILES"])

X_test = np.array(X_test, dtype=np.float32)
X_test = np.nan_to_num(X_test)

# ============================================================
# NORMALIZATION
# ============================================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ============================================================
# MODEL
# ============================================================

def build_model(input_dim):

    inputs = layers.Input(shape=(input_dim,))

    x = layers.Dense(512, activation='relu')(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.BatchNormalization()(x)

    for _ in range(1):  # keep structure similar
        x = layers.Dense(256, activation='relu')(x)

    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.3)(x)

    outputs = layers.Dense(3, activation='sigmoid')(x)

    model = Model(inputs, outputs)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=5e-5,  # LOWER LR (CRITICAL)
            clipnorm=1.0
        ),
        loss="mse",
        metrics=["mae"]
    )

    return model

# ============================================================
# TRAIN
# ============================================================

def train_model():

    model = build_model(X_train.shape[1])

    print("NaN in X:", np.isnan(X_train).any())
    print("NaN in y:", np.isnan(y_train).any())

    model.fit(
        X_train,
        y_train,
        epochs=15,
        batch_size=16,
        validation_split=0.2,
        verbose=1
    )

    return model

# ============================================================
# DISEASE SIMULATION
# ============================================================

DISEASE_DB = {
    "inflammation": {"weight": 0.8, "recovery": 0.05},
    "cancer": {"weight": 0.9, "recovery": 0.03},
    "diabetes": {"weight": 0.75, "recovery": 0.04}
}

def simulate_from_prediction(pred, disease):

    pred = np.nan_to_num(pred, nan=0.5)
    pred = np.clip(pred, 1e-6, 1 - 1e-6)

    binding, pathway, toxicity = pred

    disease_info = DISEASE_DB.get(
        disease.lower(),
        {"weight": 0.8, "recovery": 0.05}
    )

    pathway_adj = pathway * disease_info["weight"]

    cellular = 1 / (1 + np.exp(-(2*binding + 3*pathway_adj)))

    severity = 1.0
    trajectory = []

    for _ in range(30):
        severity *= (1 - cellular * disease_info["recovery"])
        severity = max(severity, 0)
        trajectory.append(round(severity, 4))

    return {
        "binding": float(round(binding * 100, 2)),
        "pathway": float(round(pathway_adj * 100, 2)),
        "toxicity": float(round(toxicity * 100, 2)),
        "cellular_response": float(round(cellular * 100, 2)),
        "trajectory": [float(x) for x in trajectory]
    }

# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":

    print("🚀 Training model...")
    model = train_model()

    print("\n🧪 Running on TEST DATA...\n")

    preds = model.predict(X_test)

    # FINAL SAFETY
    preds = np.nan_to_num(preds, nan=0.5)
    preds = np.clip(preds, 1e-6, 1 - 1e-6)

    for i in range(min(5, len(preds))):
        print(f"\nSMILES: {test_smiles[i]}")
        print(simulate_from_prediction(preds[i], "inflammation"))